### ISSUE TITLE
Simple Question *.clog keyfile 

### ISSUE THREAD

**Issue by hairypaulsack** [klensy/wt-tools#35]
Just curious why a key file is needed to un-xor the .game_logs\*.clog? 

Was this per request of Gaijin or did you feel the need to do it for some reason? I guess there is also the scenario where the methods you use to do the unpacking didn't work with the .clog files and that you knew there was an extra layer of security for the logs?

I have the key, or a working copy of the key, just have to use it in ,vbs script or compiled .vbs script. Was unable to use the xor key in a keyfile with your clog_unpacker.

Besides just being curious, I also am having trouble with tailing the file. If I use the compiled .vbs script I can only decrypt .clog files that war thunder doesn't have a handle on. If I use the .vbs script in its raw form, I can tail the file but there seems to be a 20Mb cap..

-divine

**Comment by klensy** [comment]
Hello.

No Gaijin' requests involved, just don't wanna share key (it's not so hard to get it).
No extra layers, xor key only (last time when i test it).
If u wanna use clog_unpacker, key should be in raw form (i.e. not text file, but binary file with size of key).

**Comment by Artoria2e5** [comment]
If you want to google it, you can find https://www.unknowncheats.me/forum/other-mmorpg-and-strategy/85949-war-thunder-2.html. Without it you can probably work out the length of the key with https://github.com/hellman/xortool.

**Comment by diVineProportion** [comment]
okay so that was really rewarding.. its been a little under two years since I fist asked the question, but messing around with it here and there a few times this last month finally did it. Thought there was a problem because it's 1/2 the size of the files that the vbs script output, but I guess this has something to do with the byte order of 'ANSI' vs 'UTF-16LE BOM' ?

@Artoria2e5 When I use xortool with -c 0x20 and -l 128 it get's like 95 success or its says its 95% sure. For the most part, the file is okay but get's those little black squared similar to CR LF NUL type, any input?

Anyway, thank you @klensy and @Artoria2e5

**Comment by Kosipusha** [comment]
@diVineProportion yes, you are correct
basically war thunder .clog file is 128 byte cycle XOR encryption
i can drop gpt generated code (python) that decodes using xortools generated key in file
done, https://github.com/Kosipusha/WT-clog-decypt (first time doing something on github)
