### ISSUE TITLE
C# BLK Unpacker Port

### ISSUE THREAD

**Issue by Kmsxkuse** [klensy/wt-tools#40]
This isnt any bugs so sorry if this is the wrong place to put this question but I was recently porting over your BLK file unpacker to C# for another project of mine. You can find it here: https://github.com/Kmsxkuse/WT-Wiki-Bot-in-CSharp/blob/master/BlkUnpacker.cs.

I was wondering where you're getting these numbers especially num_of_units_in_file_v3_offset and units_length_type_v3_offset along with the equation that hashed the IDs. I have no experience with reading the hex of files so if you can point me where you got this information, I will be very grateful.

**Comment by klensy** [comment]
Hi. Somewhere in file should be counter of any entities used later, so i started to looking it, comparing multiple blks, all other numbers i've got by using the same method - comparing.

Open blk files in some hex editor, 010 Editor for example, to view and navigate inside blk file.

Fun project of yours! I've started similar some time ago - https://github.com/klensy/klensy.github.io but stopped it, because i don't know the good way to display so much data.
